/**
 * VERIFY-AI — clinical assessment runner (all three study arms).
 *
 * Walks the participant through the 16 questions (8 scenarios × Question
 * A and B) one at a time, rendering in place rather than navigating, and
 * saving progress to localStorage after every question. Nothing is
 * written to Firestore here — the single Firestore write still happens
 * once, at final submission (complete.html).
 *
 * What each arm sees (this is the core of the study design — see
 * js/participant/study-arm.js):
 *
 *   No-AI          scenario → question → answer.
 *                  No AI suggestion is rendered, no AI markup exists in
 *                  the DOM, no AI request is made (none is made in ANY
 *                  arm — AI output is pre-generated and locked in
 *                  case-data.js).
 *
 *   Standard AI    scenario → question → AI suggestion panel → answer.
 *                  The suggestion is labelled as an AI suggestion and is
 *                  never pre-selected for the participant. The VERIFY-AI
 *                  workflow is not rendered.
 *
 *   AI + VERIFY-AI scenario → question → AI suggestion panel →
 *                  six-step VERIFY-AI check → answer. The final answer
 *                  cannot be submitted until all six steps are complete.
 *
 * Research integrity: no correctness feedback of any kind is shown during
 * the assessment, and the answer key is not present in the client.
 */
import { QUESTIONS, TOTAL_QUESTIONS, CONFIDENCE_PROMPT } from "./case-data.js";
import { getParticipantDraft, getStudyProgress, saveStudyProgress } from "../utils/local-storage.js";
import { resolveArm, armShowsAi, armShowsVerifyWorkflow, isValidArm } from "./study-arm.js";
import {
  renderVerifyWorkflow,
  collectAndValidate,
  independentAnswerFrom,
} from "./verify-workflow.js";

function escapeHtml(value) {
  return String(value).replace(
    /[&<>"']/g,
    (ch) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[ch])
  );
}

function getProgress(arm) {
  const stored = getStudyProgress();
  if (stored && Array.isArray(stored.responses)) {
    // Keep the arm the participant started in; never re-assign mid-study.
    if (!isValidArm(stored.studyArm)) stored.studyArm = arm;
    return stored;
  }
  return { currentIndex: 0, studyArm: arm, responses: [] };
}

function renderBlocked(message) {
  const root = document.getElementById("case-root");
  if (!root) return;
  root.innerHTML = `<p class="case-blocked">${escapeHtml(message)}</p>`;
}

/**
 * The locked AI suggestion panel. Rendered ONLY for arms where
 * armShowsAi(arm) is true — for the No-AI arm this function is never
 * called and none of this markup reaches the page.
 */
function renderAiPanel(question) {
  const ai = question.aiSuggestion;
  if (!ai) return "";
  return `
    <section class="ai-panel" aria-labelledby="ai-panel-heading">
      <p class="ai-panel__tag" id="ai-panel-heading">AI suggestion</p>
      <p class="ai-panel__answer">${escapeHtml(ai.optionLabel)}</p>
      <p class="ai-panel__disclaimer">
        This is a suggestion generated by an AI system. It has not been
        selected for you, it may be wrong, and you are responsible for the
        final answer you submit.
      </p>
    </section>
  `;
}

function renderQuestion(progress, arm) {
  const root = document.getElementById("case-root");
  if (!root) return;

  const index = progress.currentIndex;
  const question = QUESTIONS[index];
  const showAi = armShowsAi(arm);
  const showVerify = armShowsVerifyWorkflow(arm);

  // Record when this question was first shown (once per question).
  if (!progress.responses[index]) {
    progress.responses[index] = {
      scenarioId: question.scenarioId,
      questionId: question.id,
      questionIndex: index,
      studyArm: arm,
      aiSuggestionShown: showAi,
      aiSuggestion: showAi
        ? { optionId: question.aiSuggestion.optionId, optionLabel: question.aiSuggestion.optionLabel }
        : null,
      verifyWorkflowShown: showVerify,
      startedAt: new Date().toISOString(),
      aiSuggestionShownAt: showAi ? new Date().toISOString() : null,
      completed: false,
    };
    saveStudyProgress(progress);
  }

  root.innerHTML = `
    <p class="case-progress">${escapeHtml(question.scenarioTitle)} · Question ${
    index + 1
  } of ${TOTAL_QUESTIONS}</p>
    <h1 class="case-title">Question ${escapeHtml(question.id)}</h1>
    <div class="case-vignette">${escapeHtml(question.vignette)}</div>

    ${showAi ? renderAiPanel(question) : ""}

    <form id="case-form" novalidate>
      ${showVerify ? renderVerifyWorkflow(question) : ""}

      <fieldset class="field choice-fieldset" id="answer-field" data-invalid="false">
        <legend>${escapeHtml(question.prompt)}${
    showAi ? " (your final answer)" : ""
  }</legend>
        <div class="choice-options choice-options--stacked" role="radiogroup" aria-label="${escapeHtml(
          question.prompt
        )}" aria-describedby="answer-error">
          ${question.options
            .map(
              (opt) =>
                `<label class="choice-option"><input type="radio" name="answer" value="${escapeHtml(
                  opt.id
                )}" /> ${escapeHtml(opt.label)}</label>`
            )
            .join("")}
        </div>
        <p class="field__error" id="answer-error">Please select an answer before continuing.</p>
      </fieldset>

      <fieldset class="field choice-fieldset" id="confidence-field" data-invalid="false">
        <legend>${escapeHtml(CONFIDENCE_PROMPT)}</legend>
        <div class="choice-options" role="radiogroup" aria-label="Confidence, 1 low to 5 high" aria-describedby="confidence-error">
          ${[1, 2, 3, 4, 5]
            .map(
              (n) =>
                `<label class="choice-option"><input type="radio" name="confidence" value="${n}" /> ${n}</label>`
            )
            .join("")}
        </div>
        <p class="field__error" id="confidence-error">Please select a confidence rating.</p>
      </fieldset>

      <div class="form-actions">
        <button class="btn btn-primary" type="submit">
          ${index + 1 === TOTAL_QUESTIONS ? "Finish assessment" : "Next question"}
        </button>
        <p class="form-status" id="case-status" role="status" aria-live="polite"></p>
      </div>
    </form>
  `;

  document.getElementById("case-form").addEventListener("submit", (event) => {
    event.preventDefault();
    handleSubmit(progress, arm, index);
  });

  window.scrollTo({ top: 0, behavior: "auto" });
}

function handleSubmit(progress, arm, index) {
  const question = QUESTIONS[index];
  const status = document.getElementById("case-status");
  const answerField = document.getElementById("answer-field");
  const confidenceField = document.getElementById("confidence-field");

  const answerInput = document.querySelector('input[name="answer"]:checked');
  const confidenceInput = document.querySelector('input[name="confidence"]:checked');

  const answerValid = Boolean(answerInput);
  const confidenceValid = Boolean(confidenceInput);

  answerField.setAttribute("data-invalid", String(!answerValid));
  confidenceField.setAttribute("data-invalid", String(!confidenceValid));

  // VERIFY-AI arm: the six-step check is mandatory and cannot be skipped.
  let verify = null;
  if (armShowsVerifyWorkflow(arm)) {
    verify = collectAndValidate();
    if (!verify.valid) {
      status.textContent =
        "Please complete every step of the VERIFY-AI check before submitting your final answer.";
      const firstInvalid = document.getElementById(verify.firstInvalidId);
      if (firstInvalid) firstInvalid.scrollIntoView({ block: "center" });
      return;
    }
  }

  if (!answerValid || !confidenceValid) {
    status.textContent = "Please complete both fields before continuing.";
    return;
  }

  const selectedOption = question.options.find((opt) => opt.id === answerInput.value);
  const aiOptionId = armShowsAi(arm) ? question.aiSuggestion.optionId : null;
  const independentAnswer = verify ? independentAnswerFrom(verify.responses) : null;

  progress.responses[index] = {
    ...progress.responses[index],
    finalAnswerOptionId: answerInput.value,
    finalAnswerLabel: selectedOption ? selectedOption.label : null,
    confidence: Number(confidenceInput.value),
    verifyResponses: verify ? verify.responses : null,
    independentAnswerOptionId: independentAnswer,
    // Only measurable where an independent answer was captured first
    // (VERIFY-AI arm). Null elsewhere rather than guessed.
    answerChangedAfterAi:
      independentAnswer === null ? null : independentAnswer !== answerInput.value,
    answerMatchesAiSuggestion: aiOptionId === null ? null : aiOptionId === answerInput.value,
    submittedAt: new Date().toISOString(),
    completed: true,
  };
  progress.currentIndex = index + 1;
  saveStudyProgress(progress);

  if (progress.currentIndex >= TOTAL_QUESTIONS) {
    window.location.href = "complete.html";
  } else {
    renderQuestion(progress, arm);
  }
}

function initFooterYear() {
  const el = document.getElementById("footer-year");
  if (el) el.textContent = String(new Date().getFullYear());
}

document.addEventListener("DOMContentLoaded", () => {
  initFooterYear();

  const draft = getParticipantDraft();
  if (!draft) {
    window.location.href = "entry.html";
    return;
  }

  const arm = resolveArm(draft);
  if (!arm) {
    renderBlocked(
      "We couldn't determine the study condition for your institution. Please contact the research team."
    );
    return;
  }

  const progress = getProgress(arm);
  if (progress.currentIndex >= TOTAL_QUESTIONS) {
    window.location.href = "complete.html";
    return;
  }

  renderQuestion(progress, progress.studyArm || arm);
});
